image: node:24-alpine

stages:
  - build_test
  - deploy

# --- PARTIE API ---

test-api:
  stage: build_test
  script:
    - cd API
    - npm install
    - npx eslint .
    - npm test

# --- PARTIE ADMIN (TP3) ---

build-admin:
  stage: build_test
  script:
    - cd admin
    - npm install
    - npm run build # Génère le dossier admin/dist/
  artifacts:
    paths:
      - admin/dist/
    expire_in: 1 hour
  only:
    - main

# --- PARTIE CLIENT VUE (TP4) ---

build-tp4:
  stage: build_test
  script:
    - cd client
    - npm install
    - npm run lint     # Validation ESLint (Étape 4 de ton sujet)
    - npm run build    # Génère le dossier client/dist/
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 hour
  only:
    - main

# --- DÉPLOIEMENT GLOBAL ---

deploy-all:
  stage: deploy
  before_script:
    # Installation des outils SSH
    - apk add --no-cache rsync openssh-client
    - eval $(ssh-agent -s)
    # Utilise la variable SSH_PRIVATE_KEY configurée dans GitLab
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Ajout de l'IP à la liste des hôtes connus pour éviter le blocage
    - ssh-keyscan 192.168.75.88 >> ~/.ssh/known_hosts
  script:
    - echo "Déploiement de l'API, de l'Admin et du Client Vue..."

    # 1. Déploiement du client Admin (TP3)
    - rsync -avz admin/dist/ p2308972@192.168.75.88:/var/www/html/admin/

    # 2. Déploiement du client Vue (TP4)
    - rsync -avz client/dist/ p2308972@192.168.75.88:/var/www/html/tp4/
    
    # 3. Déploiement et relance de l'API (Node.js)
    # Remplace /home/p2308972/mon-api par ton vrai chemin sur la VM
    - rsync -avz API/ p2308972@192.168.75.88:/home/p2308972/api-node/
    - ssh p2308972@192.168.75.88 "cd /home/p2308972/api-node && npm install && pm2 restart all || pm2 start server.js"

  only:
    - main