image: node:24-alpine

stages:
  - build_test
  - deploy

# Job de Build et Test pour l'API
test-api:
  stage: build_test
  script:
    - cd API              # ou le nom de ton dossier API
    - npm install
    - npx eslint .        # Vérification syntaxique demandée au 2.1
    # - npm test          # Si tu as des tests unitaires
  only:
    - main                # Ne se déclenche que sur la branche principale

# Job de Déploiement sur la VM
deploy-api:
  stage: deploy
  script:
    # Ici on utilise SSH pour envoyer les fichiers et redémarrer PM2
    # C'est la partie la plus technique qui utilise l'utilisateur gitlabci
    - echo "Déploiement en cours..."
  only:
    - main